# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loteria.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rloteria.proto\x12\x07loteria\"p\n\x0eLoteriaRequest\x12\x0f\n\x07loteria\x18\x01 \x01(\t\x12\r\n\x05\x66luxo\x18\x02 \x01(\t\x12\x10\n\x08\x63oncurso\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_concursos\x18\x04 \x01(\x05\x12\x13\n\x0btotal_geral\x18\x05 \x01(\x05\"\"\n\x0fLoteriaResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2T\n\x0eLoteriaService\x12\x42\n\rEnviarLoteria\x12\x17.loteria.LoteriaRequest\x1a\x18.loteria.LoteriaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loteria_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOTERIAREQUEST']._serialized_start=26
  _globals['_LOTERIAREQUEST']._serialized_end=138
  _globals['_LOTERIARESPONSE']._serialized_start=140
  _globals['_LOTERIARESPONSE']._serialized_end=174
  _globals['_LOTERIASERVICE']._serialized_start=176
  _globals['_LOTERIASERVICE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
